### ISSUE TITLE
Issue Removed from Project

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#18]
When an issue is removed from a project, the matching project: <project> label should be removed from it.

### Hook

**hook:** project_card 
**action:** deleted

### Actions

- [x] get project name from URL / id issue was removed from

- [x] get all repository labels

- [x] get the issue number the project card is associated to

- [x] match project that the issue was removed from to a `project: <project>` label

- [x] remove the matching `project: <project>` label from the issue

**Comment by LiamMahoney** [comment]
Having an issue with the `DELETE /repos/:owner/:repo/issues/:issue_number/labels/:name` request not properly returning a response to me. 

I'm trying to `JSON.parse(response)` but it's throwing the following error:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/var/www/scrummy/utils/request.js:131:32)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

It looks like the `res.on('data',() => {})` event is never happening. If I set a break point within that event handler and a breakpoint on the `res.on('done')` event handler the done handler catches first.

I assumed that there was a "Delete Labels" endpoint similar to the "Add Labels" endpoint that accepts a list of label names. It appears that this endpoint exists and works similarly, but the response may be broken on it. The label was getting deleted properly from the issue while trying to use that endpoint. 

Going to edit the removeLabel method to use the documented 'Remove a label from an issue' endpoint.

**Comment by LiamMahoney** [comment]
The change above appears to have fixed the issue I was having.

**Comment by LiamMahoney** [comment]
Getting the following error when an issue is removed from a project.

```
2020-05-13 01:28:50 [error] Error: couldn't find a project card for issue #24 that matches the label 'project: test project 1'
    at projectLabelRemovedFromIssue (/var/www/scrummy/core/states/issue.js:694:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.issueUnlabeled (/var/www/scrummy/core/states/issue.js:663:24)
    at async issues (/var/www/scrummy/core/hooks/issues.js:21:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:24:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
Decided to return string instead of throwing an error when a project card in the matching project label could not be found.
