### ISSUE TITLE
`project: <project>` Label Removed from Issue

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#28]
When a `project: <project>` label is removed from an issue, the issue's associated project card in that project should be deleted.

## Hook

**hook:** issues
**action:** unlabeled

## Actions

- [x] get the project name from the label removed

- [x] get all of the issue's project cards

- [x] find the project card that's in the project above

- [x] delete that project card

**Comment by LiamMahoney** [comment]
Functionality is working, but experiencing error with parsing the JSON in the response of the request. I'm thinking it's because the response is not JSON.. Going to see if I can check the response headers in the return of the request.del function

**Comment by LiamMahoney** [comment]
Problems:
1. Not seeing a `content-type` header.. not sure if i'm just missing it?
```javascript
{
  access-control-allow-origin:"*"
  access-control-expose-headers:"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, 
  X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"
  connection:"close"
  content-security-policy:"default-src 'none'"
  date:"Mon, 13 Apr 2020 01:05:16 GMT"
  referrer-policy:"origin-when-cross-origin, strict-origin-when-cross-origin"
  server:"GitHub.com"
  status:"204 No Content"
  strict-transport-security:"max-age=31536000; includeSubdomains; preload"
  vary:"Accept-Encoding, Accept, X-Requested-With"
  x-accepted-oauth-scopes:"public_repo, repo"
  x-content-type-options:"nosniff"
  x-frame-options:"deny"
  x-github-media-type:"github.inertia-preview; format=json"
  x-github-request-id:"B5B6:6D95:4C8904:D30377:5E93BACC"
  x-oauth-scopes:"admin:org, read:gpg_key, read:public_key, read:repo_hook, repo, user"
  x-ratelimit-limit:"5000"
  x-ratelimit-remaining:"4982"
  x-ratelimit-reset:"1586742625"
  x-xss-protection:"1; mode=block"
}
```

2. would need to refactor the http request in `requests.del` because the response object, `res`, isn't available to the `end` event right now

**Comment by LiamMahoney** [comment]
For now I'm going to check if the response has a value, if it does I'm assuming it's JSON parseable. There has to be a better way to do this. Left FIXME: comment

**Comment by LiamMahoney** [comment]
Getting the following error when a Project label is removed from an issue:

```
2020-05-13 01:24:23 [error] Error: expected 200 received 404 - DELETE /repos/LiamMahoney/scrummy/issues/24/labels/project:%20test%20project%201: Label does not exist
    at Object.handleRest (/var/www/scrummy/utils/request.js:210:19)
    at Object.removeLabel (/var/www/scrummy/core/actions/issue.js:79:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async normalProjectCardDeleted (/var/www/scrummy/core/states/issue.js:215:16)
    at async Object.projectCardDeleted (/var/www/scrummy/core/states/issue.js:189:24)
    at async projectCard (/var/www/scrummy/core/hooks/project_card.js:15:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:22:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
going to refactor findProjectLabel to take in a list of labels to search through.
* removes the need for the repoOwner and repoName parameters
* functions that depend on this (these will now need to get the labels before calling)
    * projectCardConverted - all repo labels
    * normalProjectCardDeleted - labels on parent object
    * normalProjectCardCreated - all repo labels
