### ISSUE TITLE
Project Label Removed from Pull Request

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#34]
When a `project: <project>` label is removed from a pull request, the associated project card in that project should be deleted.

## Hook

**hook:** pull_request
**action:** unlabeled

**Comment by LiamMahoney** [comment]
getting 

```
2020-04-28 01:49:32 [error] Error: expected 200 received 404 - DELETE /repos/LiamMahoney/scrummy/issues/33/labels/project:%20test%20project%201: Label does not exist
    at Object.handleRest (/var/www/scrummy/utils/request.js:210:19)
    at Object.removeLabel (/var/www/scrummy/core/actions/issue.js:79:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async normalProjectCardDeleted (/var/www/scrummy/core/states/issue.js:215:16)
    at async Object.projectCardDeleted (/var/www/scrummy/core/states/issue.js:189:24)
    at async projectCard (/var/www/scrummy/core/hooks/project_card.js:15:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:22:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

error when the project label is removed.

Either:
1. normalProjectCardDeleted needs to check if the issue has the project label that matches the project that the Issue / PR was just removed from
2. refactor findProjectLabel to take in a list of labels to search through
    * findProjectLabel currently gets all of the labels in the repo and matches it to the project url that's passed in
    * would replace the get repo labels with the issue / pr labels from the webhook payload
3. make new function similar to findProjectLabel that checks for labels within the issue / pr (this is pretty much the same as 2, I don't think this one should be considered)

**Comment by LiamMahoney** [comment]
Getting the following error when a project label is removed from a pull request

```
2020-05-13 01:21:42 [error] Error: couldn't find a project card for issue #35 that matches the label 'project: test project 1'
    at projectLabelRemovedFromPR (/var/www/scrummy/core/states/pull_request.js:148:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.PullRequestUnlabeled (/var/www/scrummy/core/states/pull_request.js:118:24)
    at async pullRequest (/var/www/scrummy/core/hooks/pull_request.js:16:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:26:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
Fixed initial issue, it was because I had a PR and the repository / owner hard coded into my graphQL query.

After fixing the above issue though I'm now getting this error, which is roughly the same issue as #28 

```
2020-05-13 01:38:52 [error] Error: expected 200 received 404 - DELETE /repos/LiamMahoney/scrummy/issues/35/labels/project:%20test%20project%201: Label does not exist
    at Object.handleRest (/var/www/scrummy/utils/request.js:210:19)
    at Object.removeLabel (/var/www/scrummy/core/actions/issue.js:79:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async normalProjectCardDeleted (/var/www/scrummy/core/states/issue.js:215:16)
    at async Object.projectCardDeleted (/var/www/scrummy/core/states/issue.js:189:24)
    at async projectCard (/var/www/scrummy/core/hooks/project_card.js:15:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:22:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
going to refactor findProjectLabel to take in a list of labels to search through.
* removes the need for the repoOwner and repoName parameters
* functions that depend on this (these will now need to get the labels before calling)
    * projectCardConverted - all repo labels
    * normalProjectCardDeleted - labels on parent object
    * normalProjectCardCreated - all repo labels

**Comment by LiamMahoney** [comment]
Refactor above appears to have worked, but now I'm getting this error, which is an issue of how do I know if the system is out of sync or if the label was removed? 

```
2020-05-13 02:03:24 [error] MissingProjectLabel: 'project: <project:>' label not found for project: 'Test Project 1'
    at matchLabel (/var/www/scrummy/core/states/issue.js:322:15)
    at findProjectLabel (/var/www/scrummy/core/states/issue.js:265:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async normalProjectCardDeleted (/var/www/scrummy/core/states/issue.js:212:29)
    at async Object.projectCardDeleted (/var/www/scrummy/core/states/issue.js:191:24)
    at async projectCard (/var/www/scrummy/core/hooks/project_card.js:15:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:22:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```
