### ISSUE TITLE
Pull Request Added to Project

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#36]
Getting the following error when a Pull Request is added to a project.

```
2020-05-13 01:26:06 [error] Error: expected 201 received 422 - POST /projects/columns/8259336/cards: Validation Failed
    at Object.handleRest (/var/www/scrummy/utils/request.js:210:19)
    at Object.addIssueToProject (/var/www/scrummy/core/actions/issue.js:175:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async projectLabelAddedToPullRequest (/var/www/scrummy/core/states/pull_request.js:67:28)
    at async Object.pullRequestLabeled (/var/www/scrummy/core/states/pull_request.js:18:24)
    at async pullRequest (/var/www/scrummy/core/hooks/pull_request.js:14:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:26:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
Not getting the error. Might've been a false positive or it was fixed by the last commit last night.

Double checked and I'm no longer getting an error for this action.
