### ISSUE TITLE
Pull Request Removed from Project

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#37]
Getting the following error when a PR is removed from a Project.

```
2020-05-13 01:30:34 [error] Error: couldn't find a project card for issue #35 that matches the label 'project: test project 1'
    at projectLabelRemovedFromPR (/var/www/scrummy/core/states/pull_request.js:148:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.PullRequestUnlabeled (/var/www/scrummy/core/states/pull_request.js:118:24)
    at async pullRequest (/var/www/scrummy/core/hooks/pull_request.js:16:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:26:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

**Comment by LiamMahoney** [comment]
Decided that instead of throwing an error a string should be returned when a project card for the matching project label couldn't be found.
