### ISSUE TITLE
Project Card Deleted

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#59]
When a project card is deleted:
* if the project card is not in a milestone project, remove the project label from the parent object
* if the project card was in a milestone project, demilestone the parent object

---

**hook:** project_card
**action:** deleted

**Comment by LiamMahoney** [comment]
Non-expected Errors
---

**Milestone Project Card** 

```text
2020-06-16 02:53:49 [info] scrummy recieved hook with type: issues and action demilestoned
2020-06-16 02:53:59 [error] Error: couldn't find a project card in the milestone project 'Testing Milestone 2' for #16
    at IssueHook.demilestonedHelper (/var/www/scrummy/core/hooks/parent_object.js:377:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async IssueHook.demilestoned (/var/www/scrummy/core/hooks/parent_object.js:128:24)
    at async issues (/var/www/scrummy/core/hooks/issues.js:28:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:24:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

Getting thrown when a milestone card is deleted.

**Non Milestone Project Card**

```text
2020-06-16 02:56:41 [info] scrummy recieved hook with type: issues and action unlabeled
2020-06-16 02:56:41 [error] Error: Couldn't find project card in project 'test project 1' for #16 after the label 'project: test project 1' was removed
    at IssueHook.projectLabelRemoved (/var/www/scrummy/core/hooks/parent_object.js:314:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async IssueHook.unlabeled (/var/www/scrummy/core/hooks/parent_object.js:84:28)
    at async issues (/var/www/scrummy/core/hooks/issues.js:22:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:24:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```

Getting thrown when a non milestone project card is deleted.
